### ISSUE TITLE
Not working on Vapor

### ISSUE THREAD

**Issue by curtisblackwell** [beyondcode/nova-tinker-tool#13]
Not sure if it's just impossible on Vapor, but I get a 500 error with the message "Writing to /home/sbx_user1051/.config/psysh is not allowed." when I try to run commands on Vapor.

**Comment by bernhardh** [comment]
Which version of laravel do you use and have you installed tinker as well?

```
composer require laravel/tinker
```

I think this package isn't supporting Laravel 6.x and Tinker 2.x

**Comment by bernhardh** [comment]
But I think your base problem is, taht it tries to write to a dir, which doesn't exists or has no rights to write. To fix this issue, just add 

```
XDG_CONFIG_HOME=/ABSOLUT_PATH_TO_YOUR_APP/storage/tinker
```

to you .env file (of course correct the path). Afterwards, create this directory and give it write permissions for the apache/nginx user.

**Comment by curtisblackwell** [comment]
This project was on hiatus and was ultimately cancelled, so I was unable to try.
